### PR TITLE
Update to Rails 7.0

### PR DESCRIPTION
**Pull request by nekketsuuu**
Please refer to each commit for the details.

Note for activerecord7-redshift-adapter-pennylane gem: I tried to use just pg gem instead, but it threw an error because the default adapter for postgresql sets `client_min_messages`, which isn't supported by Redshift.

- https://github.com/rails/rails/blob/v7.0.8.1/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L864
- https://github.com/rails/rails/blob/v7.0.8.1/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L241-L244

So I've decided to use a dedicated adapter for Redshift and ActiveRecord 7. I've chosen https://rubygems.org/gems/activerecord7-redshift-adapter-pennylane over <https://rubygems.org/gems/activerecord7-redshift-adapter>, since a repository of the former gem is at least public, unlike the latter.

### CODE REVIEW

**Comment by eagletmt** [comment]
> I tried to use just pg gem instead, but it threw an error because the default adapter for postgresql sets `client_min_messages`, which isn't supported by Redshift.

How about using pg gem directly without ActiveRecord? I think ActiveRecord features are not necessary for Redshift queries.

**Comment by nekketsuuu** [comment]
> How about using pg gem directly without ActiveRecord? I think ActiveRecord features are not necessary for Redshift queries.

True, we already implement adapters without AR for BigQuery and Presto. I just don't want to change the whole implementation of DataSourceAdapters::RedshiftAdapter in this pull request. Let me check if we can modify RedshiftAdapter with small changes.

**Comment by nekketsuuu** [comment]
I've switched to pg gem by https://github.com/cookpad/dmemo/pull/341 & https://github.com/cookpad/dmemo/pull/342, and merge that changes to this patch.

@cookpad/infra Please review this 🙏

**Review by eagletmt — APPROVED** [review]

**Review by hfm — APPROVED** [review]

**Comment by nekketsuuu** [comment]
Thanks for the reviews 🙏

**Pull request merged**
